version: '3'
services:
  # ====================
  # MySQL
  # ====================
  db:
    platform: linux/x86_64 # for Apple silicon
    image: "mysql:latest"
    ports:
      - "3306:3306"
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    # The command that will be run in the container
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # Named volumes and paths on the host mapped to paths in the container
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
  # ====================
  # Redis
  # ====================
  redis:
    platform: linux/x86_64 # for Apple silicon
    image: "redis:latest"
    ports:
      - "6379:6379"
    # Named volumes and paths on the host mapped to paths in the container
    volumes:
      - "./redis:/data"